# Generated by Django 2.1.3 on 2018-11-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_todolist_assigned'),
        ('blog', '0012_auto_20181117_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teamtable'),
        ),
    ]
