# Generated by Django 2.1.4 on 2018-12-11 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_team_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='team_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable'),
        ),
    ]
