# Generated by Django 2.1.2 on 2018-11-16 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='length has to be 10', regex='^.{10}$')])),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clientlist',
            unique_together={('name', 'phno', 'email')},
        ),
    ]
