# Generated by Django 2.1.3 on 2018-11-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181118_1832'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlist',
            name='company_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
    ]
