# Generated by Django 2.1.4 on 2018-12-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20181207_0831'),
        ('clients', '0002_clientlist_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlist',
            name='user',
        ),
        migrations.AddField(
            model_name='clientlist',
            name='team_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable'),
        ),
    ]
