# Generated by Django 2.1.3 on 2018-11-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
