# Generated by Django 2.1.3 on 2018-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Jobtitle',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Project Manager', 'Project Manager'), ('Employee', 'Employee')], default='', max_length=100),
        ),
    ]
