# Generated by Django 2.1.3 on 2018-11-13 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20181112_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='teamtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=100)),
                ('company_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
        ),
        migrations.AddField(
            model_name='groupusertable',
            name='team_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable'),
        ),
        migrations.AddField(
            model_name='groupusertable',
            name='user_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teamtable',
            unique_together={('company_name', 'group_name')},
        ),
        migrations.AlterUniqueTogether(
            name='groupusertable',
            unique_together={('team_details', 'user_name')},
        ),
    ]
