# Generated by Django 2.1.3 on 2018-11-17 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20181113_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='to_notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=100)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('team_details', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable')),
                ('user_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='work_assigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Todolist')),
            ],
        ),
        migrations.AddField(
            model_name='to_notify',
            name='work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Todolist'),
        ),
    ]
