# Generated by Django 2.1.3 on 2018-11-17 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181117_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
