# Generated by Django 2.1.3 on 2018-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181118_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_notify',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='project_name',
            field=models.CharField(default=1234, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
