# Generated by Django 2.1.3 on 2018-11-18 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20181118_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_notify',
            old_name='user_name',
            new_name='user_notify',
        ),
        migrations.RenameField(
            model_name='work_assigned',
            old_name='user_name',
            new_name='user_assign',
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('title', 'user_name')},
        ),
    ]
