# Generated by Django 2.1.3 on 2018-11-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20181118_1826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together=set(),
        ),
    ]
