# Generated by Django 2.1.3 on 2018-11-18 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20181118_1827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('title', 'user_name')},
        ),
    ]
