# Generated by Django 2.1.4 on 2018-12-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181118_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='upload',
            field=models.FileField(upload_to='files'),
        ),
    ]
