# Generated by Django 2.1.4 on 2018-12-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20181206_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='filetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.CharField(default='', max_length=100)),
                ('filename', models.CharField(default='', max_length=100)),
                ('parentfolder', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable')),
            ],
        ),
        migrations.CreateModel(
            name='foldertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderid', models.CharField(default='', max_length=100)),
                ('foldername', models.CharField(default='', max_length=100)),
                ('team_details', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable')),
            ],
        ),
    ]
