# Generated by Django 2.1.4 on 2018-12-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_filetable_foldertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetable',
            name='parentfolder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.foldertable'),
        ),
    ]
