# Generated by Django 2.1.4 on 2018-12-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
