# Generated by Django 2.1.4 on 2018-12-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20181207_0831'),
        ('chat', '0006_auto_20181208_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='staff_only',
        ),
        migrations.AddField(
            model_name='room',
            name='teamdetails',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable'),
        ),
    ]
