# Generated by Django 2.1.3 on 2018-11-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_tasklist_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='work',
        ),
    ]
