# Generated by Django 2.1.4 on 2018-12-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('put_calendar', '0004_check_date1_team_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_date1',
            name='team_details',
        ),
    ]
