# Generated by Django 2.1.4 on 2018-12-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20181207_0831'),
        ('put_calendar', '0005_remove_check_date1_team_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_date1',
            name='team_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teamtable'),
        ),
    ]
